### ISSUE TITLE
the result of primerForge

### ISSUE THREAD

**Issue by aiqubo** [dr-joe-wirth/primerForge#15]
Hi joe, 

Thank you for your primerForge,
I have some confusion for the result of primerForge,

Can this software input the following sequence as a ingroup file, and output some primers that can cover the following genomes?
It seem that the result file contain a large number of primers, but none of them can cover the entire genome.

'''
>CP012805.1 Streptococcus anginosus strain J4211, complete genome
>CP044219.1 Streptococcus mutans strain NCH105 plasmid pMut1, complete sequence
>CP044220.1 Streptococcus mutans strain NCH105 plasmid pMut2, complete sequence
>CP044221.1 Streptococcus mutans strain NCH105 chromosome, complete genome
>CP066055.1 Streptococcus constellatus strain FDAARGOS_1015 chromosome, complete genome
>CP067992.1 Streptococcus mitis strain S022-V7-A3 chromosome, complete genome
>FR873482.1 Streptococcus salivarius JIM8777 complete genome
>LS483436.1 Streptococcus intermedius strain NCTC11324 genome assembly, chromosome: 1
>NZ_LS483346.1 Streptococcus sanguinis strain NCTC11085 chromosome 1, complete sequence

'''

Qubo

[result.xlsx](https://github.com/dr-joe-wirth/primerForge/files/14850192/result.xlsx)

**Comment by dr-joe-wirth** [comment]
@aiqubo I'm not sure I understand your question. Looking at your results, it appears you ran `primerForge` on a single genome. It is designed to take multiple genomes at once and find shared primer pairs that can be used in all the input genomes.

> It seems the result file contain a large number of primers, but none of them can cover the entire genome.

I'm not sure what you're asking. Primers are used in PCR and are not intended to cover the entire genome. They should amplify specific regions of the genome. It is not possible to design a pair of primers that "can cover the entire genome."

**Comment by aiqubo** [comment]
Thank you for your quick response to my question, I want to design a pair of primers that can amplify the above 9 sequences of  Streptococcus species, I would like to know if it can be achieved using primerForge？

**Comment by dr-joe-wirth** [comment]
Sure that seems like it would work.
