### ISSUE TITLE
How to run tests

### ISSUE THREAD

**Issue by mbhall88** [dr-joe-wirth/primerForge#21]
This issues is part of the JOSS review https://github.com/openjournals/joss-reviews/issues/6850

In relation to the documentation guideline **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?

I see there is a unit tests directory in your `bin/` directory, but I don't see any documented way of running the tests - doesn't seem to be run on the CI so I couldn't figure it out.

**Comment by dr-joe-wirth** [comment]
Sorry about this. The instructions are in the README.md.

**Comment by mbhall88** [comment]
Out of interest. You say tests may take three hours to run. How come it takes so long?

**Comment by dr-joe-wirth** [comment]
It will run the software first, on a test case of five genomes which takes some time. The tests in `results_test.py` make sure that the results are sound and congruent with the input genomes.
