### ISSUE TITLE
Multiplex primers

### ISSUE THREAD

**Issue by dr-joe-wirth** [dr-joe-wirth/primerForge#34]
**Is your feature request related to a problem? Please describe.**
It may be useful to return a list of primers that can be used in multiplex PCRs

**Describe the solution you'd like**
Honestly not sure.

**Additional context**
A colleague suggested that this could be useful for surveillance and/or diagnostics.

**Comment by lskatz** [comment]
I'd suggest a separate package to parse primer bed files so that you don't get too much feature creep

**Comment by dr-joe-wirth** [comment]
closing this issue; not going to implement this feature at this time.
