### ISSUE TITLE
tested on plants? 

### ISSUE THREAD

**Issue by colindaven** [dr-joe-wirth/primerForge#39]
Hi,

thanks for this nice modern tool. I could install easily via `pixi shell` btw.

I'm wondering if the tool will be fast enough for eukaryotes, eg plants? I saw you've tested on E. coli I think in the paper. Does that mean you should only use small regions (targets, not whole chromosomes/genomes) or is the approach only intended for prokaryotes. I could also try to optimize if you believe it is worth the effort.

Which are the slowest steps for example or are there inherent limitations. I was thinking of taking homeologous regions from brassica (1 Gbp genome) or Wheat 15+ Gbp genome and trying to use these as in and outgroups. Or do you think other software like NCBI primerblast (I believe it lacks an MSA step) or GSP https://academic.oup.com/bioinformatics/article/32/15/2382/1743425 might be more suited to this task ?

Thanks,
Colin

**Comment by dr-joe-wirth** [comment]
Hey Colin,

I think it could work on plants. It is a kmer-based approach, so it should work on any genbank or fasta file. However, I do anticipate it to slow down a lot on genomes in the Gbp range, especially if there are very few contigs.

In my tests with `primerForge`, the slowest part is getting candidate kmers. This combines two sub-steps:

1. get all the kmers that appear once in each genome and are shared in all in group genomes
2. evaluate those kmers for their suitability as primers

When I ran the _E. coli_ dataset with `v1.5.1`, the total runtime was 13min; 11min was spent finding and evaluating kmers.

I am happy to help you get this working on your genomes in a reasonable amount of time. Would you be willing to suggest a few genomes for use as test cases? Maybe 2-3 ingroup genomes and 2-3 outgroup genomes? I would only need NCBI accession numbers and then I can test them out.

If you have ideas for how to cutdown on kmer generation, like a heuristic to skip certain regions of the genome, then I am all ears.

**Comment by colindaven** [comment]
Hey Joe,

thanks for the information and your willingness to test.

I hadn't actually realized it was kmer based - what is the default kmer size ?

I don't want to waste your time, so I'll get into the package first and try out some different tests and small genomes. If the outputs are informative for the users I'll try it on medium and even large genomes. This will take a bit of time though so I will get back to you later on.

They seem to want to do comparisons between small regions eg 1-2000 bp and whole genomes. Are these kind of size mismatched efforts doomed to fail or is this one intended use case ?

Thanks
Colin

**Comment by dr-joe-wirth** [comment]
If you type `primerForge --help` it will tell you the default values for all the parameters.

That could work. The important thing is that all the files are the same format (fasta or genbank is allowed). However, it may fail because of biological reasons. For example, it can't find shared kmers if the 2000bp region is very distinct from the other genomic sequences in the ingroup.

Please keep me posted. I'm interested to know how it turns out.

**Comment by dr-joe-wirth** [comment]
closing this issue. feel free to reopen if necessary

**Comment by colindaven** [comment]
Feedback so far - seems to be working well on plant regions of eg 10kbp, but I had trouble getting it to work on whole genomes (eg 3 Arabidopsis genomes).

I'll provide more feedback when I can get those with more expertise and real needs to give it a go and check the results in detail.
