### ISSUE TITLE
create `pip` installation

### ISSUE THREAD

**Issue by dr-joe-wirth** [dr-joe-wirth/primerForge#6]

**Comment by rpetit3** [comment]
Feel free to ping me if you want help with this

**Comment by dr-joe-wirth** [comment]
@rpetit3 i'm open to any help you can offer to help me get started.

**Comment by dr-joe-wirth** [comment]
@rpetit3 I have created a `pip` installation. if you have a free moment i'd appreciate any feedback you might have.
